source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftPrayTimes_Example', :exclusive => true do
  pod "SwiftPrayTimes", :path => "../"
end

target 'SwiftPrayTimes_Tests', :exclusive => true do
  pod "SwiftPrayTimes", :path => "../"

  
end
